---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache
      apt:
        update_cache: 'yes'
        cache_valid_time: 3600

    - name: CA Certificates
      apt:
        name: ca-certificates

    - name: Install curl
      apt:
        name: curl

    - name: Download JDK
      apt:
        name: java-1.8.0-openjdk-devel